framework:
    default_locale: fr
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - fr
        providers:
            lokalise:
                dsn: '%env(LOKALISE_DSN)%'
                domains: ['messages', 'forms', 'security', 'validators']
                locales: ['fr', 'en', 'ua']