# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
     photos_directory: '%kernel.project_dir%/public/styles/image'
     session_idle_timeout: 30
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false # Whether the service should be made public
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
        # Define your services here
    App\Entity\LigneCommande: ~
    App\Repository\LigneCommandeRepository: ~
    App\Entity\Commande: ~
    App\Repository\CommandeRepository: ~
    App\Entity\Produit: ~
    App\Repository\ProduitRepository: ~
    App\Entity\User: ~
    App\Repository\UserRepository: ~
    App\Entity\Entreprise: ~
    App\Repository\EntrepriseRepository: ~
    App\Command\DeleteOldCommandsCommand:
        tags: [console.command]
    # App\EventListener\SessionTimeoutListener:
    #     tags:
    #         - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    App\Security\SessionIdleHandler:
        arguments:
            $session: '@session'
        tags:
            - { name: 'kernel.event_subscriber' }
            # - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

  
   

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

